### ISSUE TITLE
Scope issue on new toot

### ISSUE THREAD

**Issue by jdenen** [martianhi/mastodon.el#1]
`mastodon-toot` returns a `403 Forbidden` error response. The error message mentions a scope issue:

```
{"error":"This action is outside the authorized scopes"}
```

Since mastodon.el registers with `"read write follow"` scopes, this doesn't make much sense.

I can use the same token from `mastodon--api-token-string` to GET posts.

```bash
curl --header "Authorization: Bearer ${TOKEN}" -sS https://mastodon.social/api/v1/statuses/1895661
```

This returns a `200` and the toot data.

**Comment by fapdash** [comment]
Can confirm, same issue.
```
HTTP/1.1 403 Forbidden
//.....
{"error":"This action is outside the authorized scopes"}
```

**Comment by jdenen** [comment]
I have the same problem using `cURL`. Looks like it's time for an issue on Mastodon itself.

```bash
curl -H "Authorization: Bearer ${TOKEN}" -H "Content-Type: application/json" -S -X POST -d '{"status":"Just cURLing. Please ignore."}' https://mastodon.social/api/v1/statuses
```

**Comment by jdenen** [comment]
Tracking issue [1367](https://github.com/tootsuite/mastodon/issues/1367) now.
