### ISSUE TITLE
Better success callback

### ISSUE THREAD

**Issue by jdenen** [martianhi/mastodon.el#11]
Right now, the success callback on a new toot opens the response buffer from `url-retrieve`. It should just message a success, perhaps with the toot `id`.

- [x] new toot
- [x] reply
- [x] boost
- [x] favourite

**Comment by saper** [comment]
In case of `mastodon-toot--favourite` the `Contacting host: mastodon.social:443` message stays there until the key is pressed (the timeline gets updated with `F`)

Initially I though it hangs in there. At least HTTP response would be clearly a confirmation things worked.

**Comment by jdenen** [comment]
@saper Boost/Favourite should have better feedback as of `232c621`. They'll message you `Boosted #12345` or `Favourited #12345` where `12345` is the toot id.

This fix will be included in the v0.4.1 release later this evening.

**Comment by saper** [comment]
@jdenden can you keep the HTTP response somewhere as the debug mode for folk learning the protocol? can be useful sometimes maybe?

**Comment by jdenen** [comment]
@saper I opened #50 for your enhancement request. Seems like a reasonable idea.
