### ISSUE TITLE
windows "cannot connect to mastodon.social:443"

### ISSUE THREAD

**Issue by andrewbanchich** [martianhi/mastodon.el#137]
is there a way to fix this on windows?

**Comment by hdurer** [comment]
I don't have Windows myself but one of the developers uses it under Windows so I'm fairly confident that this can work.
It's there any more information that Emacs gives you to understand what exactly the issue might be?

**Comment by jfmcbrayer** [comment]
Do you have either gnutls or openssl installed on Windows? Because emacs will need one of those to make an https connection to your instance.

**Comment by andrewbanchich** [comment]
Not sure. I will ask IT about it. Thanks!
