### ISSUE TITLE
Use correct buffer modes and maybe add run hooks for customisation

### ISSUE THREAD

**Issue by hdurer** [martianhi/mastodon.el#138]
User `Seylerius` on Matrix reported:

> Okay, I'm noticing that `*mastodon-home*` buffers spawn in help mode, rather than mastodon-mode.
> This is not a problem for `*mastodon-federated*` buffers, which spawn in mastodon-mode.
> 
> Similarly, `*new-toot*` buffers spawn in `fundamental-mode`, which makes hooking flyspell a bit more complicated.

**Comment by sableseyler** [comment]
Interesting. I think it was an issue of not loading correctly. Now that I've restarted emacs, rather than directly evaluating the `use-package` block, it's working properly. Weirdness.

**Comment by hdurer** [comment]
Besides: you should also have `mastodon-mode-hook` and `mastodon-toot-mode-hook` where you can add customisations.

**Comment by hdurer** [comment]
Possibly related: I just had the case where the local timeline did not correctly show in mastodon mode, presumably because of some error being thrown during page setup - I saw an "bad url" error while it loaded.

After a short while this issue sorted itself out, presumably because the toot with the offending avatar was no longer in the initial list of toots.

**Comment by jdenen** [comment]
It looks like @seylerius fixed his initial issue. I'm going to close this for now.
