### ISSUE TITLE
End of file while parsing JSON

### ISSUE THREAD

**Issue by DriXse** [martianhi/mastodon.el#141]
Hi,

I use M$ Windows with [EmacsW64](https://github.com/zklhp/emacs-w64) with gnutls. 

I try with other instance, but same error

```
Contacting host: mastodon.social:443
json-read: End of file while parsing JSON
```

Thanks.

**Comment by ghost** [comment]
I have the same when using mastodon behind a proxy. Any hints on how to debug?

**Comment by seanlynch** [comment]
I am having exactly the same problem on Linux, so this is not Windows-specific. toggle-debug-on-error doesn't bring up the debugger when it happens for some reason.

I'm on GNU Emacs 26.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.8)
 of 2019-04-12 under Arch Linux. Also shows up in remacs.

**Comment by ghost** [comment]
I'm also suffering from this bug. Any ideas? Unlike @ghost I am not behind a proxy. I am on GNU/Linux using Emacs 26.2

**Comment by martianhi** [comment]
i think this just happens when the request fails or the server does something flakey. feel free to reopen if you still see this issue.
