### ISSUE TITLE
crash in plstore-put on first run

### ISSUE THREAD

**Issue by bremner** [martianhi/mastodon.el#144]
This is with 0.7.0 from melpa-stable (there's no tag for 0.7.1)
Duplicated in emacs -q, with default setting of **mastodon-instance-url**
``` lisp
Debugger entered--Lisp error: (wrong-type-argument symbolp (id . "240"))
  symbol-name((id . "240"))
  plstore-put([#<buffer  plstore /home/bremner/.emacs.d/mastodon.plstore> nil nil nil nil] "mastodon" ((id . "240") (name . "mastodon.el") (website . "https://github.com/jdenen/mastodon.el") (redirect_uri . "urn:ietf:wg:oauth:2.0:oob") (client_id . "hex-string") (client_secret . "hex-string")) nil)
  mastodon-client--store()
  mastodon-client()
  mastodon-auth--generate-token()
  mastodon-auth--get-token()
  mastodon-auth--access-token()
  mastodon-http--get("https://mathstodon.xyz/api/v1/timelines/home")
  mastodon-http--get-json("https://mathstodon.xyz/api/v1/timelines/home")
  mastodon-tl--init("home" "timelines/home" mastodon-tl--timeline)
  mastodon-tl--get-home-timeline()
  mastodon()
  funcall-interactively(mastodon)
  call-interactively(mastodon record nil)
  command-execute(mastodon record)
  execute-extended-command(nil "mastodon" "mastod")
  funcall-interactively(execute-extended-command nil "mastodon" "mastod")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by erkin** [comment]
I can also reproduce this with a clean setup. I'm inclined to guess it's caused by [`(plstore-put)`](https://github.com/emacs-mirror/emacs/blob/master/lisp/plstore.el#L359) expecting a string, a plist and an optional plist; but receiving a string, an **alist** and nil instead, according to the error message.

I think it's because when [`(json-read-from-string)`](https://github.com/jdenen/mastodon.el/blob/master/lisp/mastodon-client.el#L66) is called, [`(json-read)`](https://github.com/thorstadt/json.el/blob/master/json.el#L65) guesses that it's an alist as opposed to plist since `json-key-type` is nil and `json-object-type` is alist by default.

**Comment by hdurer** [comment]
That's weird.  You even point to our code where we are let-binding `json-object-type` to be `plist` around the call to `json-read-from-string`.

**Comment by wilhelmy** [comment]
I'm experiencing the same problem and now I'm unsure how to debug it.

**Comment by baby-gnu** [comment]
I had the same issue.

I deleted the package from the Emacs package manager then reinstalled it and everything is working correctly now:

`GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-05-07, modified by Debian`

**Comment by erkin** [comment]
I can confirm that the latest update on MELPA fixes this issue for me.

**Comment by jb55** [comment]
I'm still getting this on a fresh install

```
GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-07-04
```

**Comment by jdenen** [comment]
I just had to replace a laptop, so I've recently re-installed Emacs (26.1) and mastodon.el. I didn't reproduce this issue.

Did you by chance have a previously created `$EMACS_HOME/mastdon.plstore` file? A fresh package install with an old plstore could be an issue. But I'm grasping a bit.

**Comment by jb55** [comment]
Hmmm I somehow got the error to go away while I was debugging this. For some reason `json-object-type` was not dynamically bound to `'plist` during the json-read calls. very mysterious...

It started working when I `debug-on-entry`'d the json-read call, and then `e` + `(setq json-object-type 'plist)`. After that it started working, even after restarting and deleting the plstore file. SPOOKY.

Now it just hangs during authentication :(

**Comment by wilhelmy** [comment]
Somehow it works for me too, now.

**Comment by fujii** [comment]
I installed mastodon-20180811.220 from Melpa today, and met this issue.
`(mastodon-client--fetch)` returned alist.
I byte-compiled mastodon-client.el, and reloaded. Then, `(mastodon-client--fetch)` returned plist.
I uploaded disassembled `mastodon-client--fetch` of before and after byte-recompiling, and the diff.
https://gist.github.com/fujii/a88a5b0ed26581a34a6a240450b2c362

**Comment by fujii** [comment]
This seems a lexical binding issue. I think mastodon-client.el needs `(require 'json)` to tell json-* are special variables.

**Comment by martianhi** [comment]
feel free to re-open if this appears again.
