### ISSUE TITLE
Why not create a general ostatus mode for all microblogging services

### ISSUE THREAD

**Issue by spiderbit** [martianhi/mastodon.el#146]
I wished I would have such a client for reddit, but if we have the luck that at least twitter and matadon and some more support a open web standard, why not use that protocol instead of writing a network specific client.

Its like making a yahoo mail client because you don't like google mail, instead of a general mail client, nearly nobody would do that, except the company behind yahoo maybe.

I mean doing A doesn't mean not doing B but still I wonder why not using that nice protocols if they exist.

**Comment by bortzmeyer** [comment]
I don't think a stub client can use Ostatus (or ActivityPub) to talk a a Mastodon server. You have to use the API and all the programs (Mastodon and GNU social, for instance) use a different API.

**Comment by jdenen** [comment]
I started mastodon.el for using Mastodon specifically, using its API documentation as reference. It may or may not work elsewhere, but supporting other APIs is not in the scope of this project.
