### ISSUE TITLE
Unknow host?

### ISSUE THREAD

**Issue by YandongZhang** [martianhi/mastodon.el#147]
Hello,

After installing, I cannot connect to the host. The error message is :
Unknown host "mastodon.social" .

Can anybody help?

3x

**Comment by hdurer** [comment]
To me this sounds like your computer cannot resolve that name to an ip address.  

 - Were you connected to the internet when this happened? 
 - Can you visit https://mastodon.social/ in a browser on your computer when that happens?  
 - Can you with your Emacs? (For emacs try `M-x eww` to use Emacs's browser.)

**Comment by YandongZhang** [comment]
Hi hdurer,

Sorry for my later response. Your answer was correct. The issue was caused by the firewall.

Thank you
