### ISSUE TITLE
Wrong type argument: symbolp

### ISSUE THREAD

**Issue by fairlygood** [martianhi/mastodon.el#148]
Hi,

Installed via MELPA. Instance url is set in emacs config. I am not asked for a user name or password when executing M-X mastodon - instead I receive the following error:

Wrong type argument: symbolp (and an ID number that increments by 1 each time)

In Messages: plstore-put: Wrong type argument: symbolp

Emacs v25.2.2 on Ubuntu 17.10

Is there anything that I can do to help debug?

**Comment by alexjgriffith** [comment]
If the error is raised with `plstore-put` receiving a `symbolp` then `mastodon-client--fetch` is probably not returning a string. The number that increments probably represents the input the the `*Message*` buffer being repeated.

If you can replicate the issue and have time could there are a few things you could do to help

1. execute `(setq debug-on-error t)` in `*scratch*` or `M-:` then try to login and post the output
2. Post the html output from your attempt to log in.

## Finding the HTML output for your login attempt

The first time you start emacs and run `M-x <ret> mastodon` there will be a buffer created with your login info: ` *http mastodon.social:443` (notes: there is a space before the first * and mastodon.social will be replaced with the address of your instance). I've copied a redacted version of mine below. You don't have to post yours, just let us know if 
1. The first line is `HTTP/1.1 200 OK`
2. the Content-Type is application/json
3. the body is actually JSON. 

```
HTTP/1.1 200 OK
Date: Mon, 26 Feb 2018 05:11:42 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: no-store
Pragma: no-cache
Vary: Accept-Encoding, Origin
Content-Encoding: gzip
ETag: W/"[redacted]"
X-Request-Id: [redacted]
X-Runtime: [redacted]
Strict-Transport-Security: max-age=31536000

{"access_token":"[redacted],"token_type":"bearer","scope":"read write follow","created_at":[redacted]}
```

**Comment by fairlygood** [comment]
Hi. This seems to have resolved itself, but I'll be sure to head back here and follow your instructions if it reoccurs.
