### ISSUE TITLE
Character counter in toot-mode buffer

### ISSUE THREAD

**Issue by jdenen** [martianhi/mastodon.el#15]
Buffers for `toot-mode` should count down characters from 500 as they are entered.

It would be nice if the countdown lived alongside the documentation from #14.

**Comment by clarkenciel** [comment]
some instance have different character counts (cybre.space has 512, witches.town has 666) is there even a way to handle this?

**Comment by jdenen** [comment]
I didn't know that. 

Perhaps the answer then is to count up from 0 and let users decide how many is too many.

**Comment by clarkenciel** [comment]
okay so the server will return a 422 if you submit a post that is too long and the body will say:
`{"error":"Validation failed: Text character limit of 512 exceeded"}`. So going with 500 will be fine if we assume that instances don't set limits to be lower. One thing we could think about is using the .social defaults and, on encountering an error like this (instances like oulipo.social or dolphin.town have other, more exotic validations) present it to the user, and where applicable add appropriate client-side validations; perhaps storing it for later.

For text length that would be easy, for the weirder instances, i dunno that's not our problem probably?

**Comment by jdenen** [comment]
Yeah, not our problem. There's no way to sanely support the outlandish/hilarious rules each instance could implement. Best to just support the vanilla Mastodon experience while not blocking the ability for other experiences to use mastodon.el.

**Comment by clarkenciel** [comment]
I'm working on this and i think i'm going to make it a customizable variable. We'll default to 500, but users can update it easily if they want to reflect their instance.

**Comment by clarkenciel** [comment]
@jdenen @alexjgriffith okay since this is being referenced elsewhere, here's my suggestion for how this looks:

```
|=========================|
  doc text....
|=========================|

toot text [9 / 500]
```

update that counter next to the text as it's written. change the face of the counter to `'warning` if the current-count exceeds the `max-count`

**Comment by jdenen** [comment]
The counter is going to move as the text is written? Because that sounds awesome.

**Comment by jdenen** [comment]
What I mean by move, is the actual location in the buffer. So

`toot text [9 / 500]` becomes `toot text continued [18/ 500]` becomes:

```
toot text continued

to a new

line [33 / 500]
```

?

**Comment by clarkenciel** [comment]
exactly the idea @jdenen !

**Comment by jdenen** [comment]
Yeah I like that.

**Comment by alexjgriffith** [comment]
Big fan of the inline counter! I now i get the impact on #14.

 I was wondering how we were going to make it consistent in the buffer mode line. I think this approach is much better!

The portion I was thinking of making into a variable would be the banner i.e. 

```
|=========================|
  doc text....
|=========================|
```
I think it will be useful the first few toots you send but after that It would be nice to swap it out. Making this is variable is not a priority by any means!

**Comment by jdenen** [comment]
Bare bones implementation is in develop now. There are some improvements that need to be made, but I think we can close this issue.
