### ISSUE TITLE
Closing a mastodon buffer while async images are still loading causes some error message to show up

### ISSUE THREAD

**Issue by hdurer** [martianhi/mastodon.el#156]
It seems that we fail to check if the buffer is still present when trying to process the result of an image fetch.

**Comment by hdurer** [comment]
Easy to reproduce: Load a timeline with lots of images and quickly press `Q` to kill the buffer.

**Comment by alexjgriffith** [comment]
Thanks for the fix, I was getting this issue after I modified `mastodon-async.el` to use the rendering in `mastodon-tl.el`.

**Comment by alexjgriffith** [comment]
Closed by #157
