### ISSUE TITLE
Should `switch-to-buffer` be `with-current-buffer`?

### ISSUE THREAD

**Issue by alexjgriffith** [martianhi/mastodon.el#158]
## Description
I noticed when streaming with media the active buffer will switch back to the mastodon buffer every time an image is loaded. This makes it impossible to do other tasks while steaming.

## Proposed Solution
I suggest switching out `switch-to-buffer` in `mastodon-media--process-image-response` with `with-current-buffer`

## Edit
Once this edit is made we can begin integrating `mastodon-async.el` into the main repo

**Comment by hdurer** [comment]
Fixed with PR #160
