### ISSUE TITLE
Open hashtags in mastodon-tl--get-tag-timeline

### ISSUE THREAD

**Issue by alexjgriffith** [martianhi/mastodon.el#167]
Rather than having tags open in the browser have them open using `mastodon-tl--get-tag-timeline`

**Comment by hdurer** [comment]
I'll have a look at this - it fits in with the work to make tab navigating interesting items in the buffer better.

**Comment by hdurer** [comment]
I have [a branch `handle-tags-links`](https://github.com/hdurer/mastodon.el/tree/handle-tags-links) ready to do this.

Waiting for a review of the two commits that this depends on before creating a PR.

**Comment by hdurer** [comment]
This has been merged into `develop` a while ago.
