### ISSUE TITLE
Send media from mastodon-toot buffer

### ISSUE THREAD

**Issue by jdenen** [martianhi/mastodon.el#18]
Attach `media_ids` to a toot send from the minor mode. Limit to four.

**Comment by hdurer** [comment]
Update: user [`@jordigh@mathstodon.xyz`](https://mathstodon.xyz/@JordiGH) has volunteered to have a stab at this.  I pointed them at my half-complete code in https://github.com/hdurer/mastodon.el/tree/post-images-wip.
