### ISSUE TITLE
Errors with notification timelines

### ISSUE THREAD

**Issue by alexjgriffith** [martianhi/mastodon.el#192]
There are a few bugs I have come across while playing around with the notification buffer.

1. [ ] Does not pass proper thread ID to the toot response buffer
2. [ ] Cannot boost mentions
3. [ ] Won't open a mention thread

**Comment by martianhi** [comment]
i copied `mastodon-tl--insert-status` to `mastodon-notifications--insert-status` and we now feed it the id. should have fixed these issues.
