### ISSUE TITLE
Show profile in major mode

### ISSUE THREAD

**Issue by jdenen** [martianhi/mastodon.el#20]
I want to be able to visit a user profile like a timeline in the major mode.

**Comment by alexjgriffith** [comment]
I have an initial version of user profile streams working.

The function `mastodon-user--get-next-author` opens a new buffer named `*mastodon-$user*`. Once the buffer is generated it inserts the users static image directly along with their note (description). 

## Layout
```
$avatar_static
$modified_byline ;; still working on
$note

$content
 | $user (@$acct)
  ------------

$content
 | $user (@$acct)
  ------------
```

## Limitations
Currently it works as well as the notifications screen. I.e. it has full functionality apart from loading new toots. For this a generalized version of `mastodon-tl--update` will have to be written. I have included this as an example in the matodon-notifications.el module.

## Example
Please note that I have not added the modified by-line yet
![screenshot 2017-04-25 01 25 36](https://cloud.githubusercontent.com/assets/6475397/25370061/1b30511e-2956-11e7-97df-c553b4e18d12.png)
