### ISSUE TITLE
[feature/patch] Add a function to copy the URL of toot at point

### ISSUE THREAD

**Issue by kaushalmodi** [martianhi/mastodon.el#207]
It would be nice to copy the URL of the toot at point using an interactive function. I would bind that to `w` in `mastodon-mode-map`.

**Comment by kaushalmodi** [comment]
I got this working with this code:

```elisp
(defun mastodon-toot-at-point ()
  "Return the toot at point as an alist.
If current toot is a Boosted toot, return the original toot."
  (let* ((this-toot (mastodon-tl--property 'toot-json))
         (orig-toot (cdr (assoc 'reblog this-toot))))
    (or orig-toot this-toot)))

(defun mastodon-get-url-of-toot-at-point ()
  "Return the URL of the toot at point as a string.
If the current toot is a Boosted toot, get the URL of the
original toot."
  (let ((toot (mastodon-toot-at-point)))
    (cdr (assoc 'url toot))))

(defun mastodon-browse-url-of-toot-at-point ()
  "Browse the URL of the toot at point.
If the current toot is a Boosted toot, browse the URL of the
original toot."
  (interactive)
  (let ((url (mastodon-get-url-of-toot-at-point)))
    (browse-url url)))

(defun mastodon-copy-url-of-toot-at-point ()
  "Copy the URL of the toot at point.
If the current toot is a Boosted toot, copy the URL of the
original toot."
  (interactive)
  (let ((url (mastodon-get-url-of-toot-at-point)))
    (prog1
        (kill-new url)
      (message "Copied toot URL: %s" url))))
```

[ref][1]

[1]: https://github.com/kaushalmodi/.emacs.d/blob/ad042e65b8cfe834b605579975e9aeeae6e46dd4/setup-files/setup-mastodon.el#L58-L88

**Comment by alexjgriffith** [comment]
It seams to work fine if i replace `browse-url` with `eww`. 

Rather than opening a thread in eww or another browser we have opted to render them as we do timelines. See `(mastodon-tl--thread)`, which is bound to `t`. If you have imagemagick installed it will scale the user thumbnails down to a less obtrusive size.

I think that `mastodon-toot-at-point` should definitely be added to `mastodon-tl`, but  I'm not quite sure where the other three fit.

**Comment by kaushalmodi** [comment]
`mastodon-toot-at-point` and `mastodon-get-url-of-toot-at-point` are just helper functions which I need in the later 2 interactive (user) functions.

> Rather than opening a thread in eww or another browser we have opted to render them as we do timelines. See (mastodon-tl--thread), which is bound to t.

I agree. Then there's not much value to add `mastodon-browse-url-of-toot-at-point` to mastodon.el.

But I find `mastodon-copy-url-of-toot-at-point` (just copying the toot URL) very useful for documentation purpose. When I write notes/attributes, I like to copy the permalink of the source where I got that info from.

**Comment by jdenen** [comment]
@kaushalmodi I agree that `mastodon-copy-url-of-toot-at-point` should be included. Feel free to PR it in if you'd like.

**Comment by kaushalmodi** [comment]
Thanks. I'm traveling at the moment. So I'll be able to get to this in about 3 weeks.

**Comment by jdenen** [comment]
No worries. Enjoy your travels.

**Comment by codingquark** [comment]
Things are already done here @kaushalmodi throw a PR? Or I can create one for you (however that might work out)

**Comment by kaushalmodi** [comment]
Sorry, I just realize this action item fell to the way side. @codingquark Please feel free to send a PR. I've got busy with few other things lately.
