### ISSUE TITLE
Support Pleroma

### ISSUE THREAD

**Issue by nono-gdv** [martianhi/mastodon.el#208]
Hi,

When trying to connect to a Pleroma instance, I get the following error message:

`Wrong type argument: listp, "Something went wrong"`

In the server log file:

```
09:35:16.874 request_id=2l7g59st1gmn3355fo0042mh [info] POST /api/v1/apps
#Ecto.Changeset<
  action: nil,
  changes: %{},
  errors: [
    client_name: {"can't be blank", [validation: :required]},
    redirect_uris: {"can't be blank", [validation: :required]},
    scopes: {"can't be blank", [validation: :required]}
  ],
  data: #Pleroma.Web.OAuth.App<>,
  valid?: false
>
{:error,
 #Ecto.Changeset<
   action: :insert,
   changes: %{},
   errors: [
     client_name: {"can't be blank", [validation: :required]},
     redirect_uris: {"can't be blank", [validation: :required]},
     scopes: {"can't be blank", [validation: :required]}
   ],
   data: #Pleroma.Web.OAuth.App<>,
   valid?: false
 >}
09:35:16.881 request_id=2l7g59st1gmn3355fo0042mh [info] Sent 500 in 7ms
```

**Comment by bortzmeyer** [comment]
It would be great if mastodon.el support Pleroma. However, https://github.com/jdenen/mastodon.el/issues/146#issuecomment-411954231 may be of interest. #146

**Comment by hdurer** [comment]
Interesting.  We *do* (try to) send those items in the post request (see `mastodon-client--register`) and in fact Mastodon itself also [considers these required](https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#registering-an-application).

**Comment by fariedt** [comment]
This occurs because `url.el` doesn't set the `Content-Type` header for POSTs on its own; see the example on [EmacsWiki](https://www.emacswiki.org/emacs/UrlPackage).  My fix:

```diff
diff --git a/lisp/mastodon-http.el b/lisp/mastodon-http.el
index 7be4467..8e46c74 100644
--- a/lisp/mastodon-http.el
+++ b/lisp/mastodon-http.el
@@ -84,6 +84,8 @@ Authorization header is included by default unless UNAUTHENTICED-P is non-nil."
 	 (append
 	  (unless unauthenticed-p
 	    `(("Authorization" . ,(concat "Bearer " (mastodon-auth--access-token)))))
+          (unless (assoc "Content-Type" headers)
+            '(("Content-Type" . "application/x-www-form-urlencoded")))
 	  headers)))
     (with-temp-buffer
       (url-retrieve-synchronously url))))
```

**Comment by lambdadog** [comment]
interestingly even after making this modification i still have the same error. 

Not seeing anything in my logs, but that may be due to my loglevel

**Comment by fariedt** [comment]
Which version of pleroma is it?  I've tested against the `develop` branch (running in production, see [this post]( https://p.node.pk/api/statuses/show/9h4Zj9NVtIBqXFdj0q.json)) and the `v0.9.999` tagged release.

You might want to remove `~/.emacs.d/mastodon.plstore` if it already exists, restart Emacs, and then try again.

**Comment by lambdadog** [comment]
was able to get it to work now, might have had some leftover bits before that I wasn't paying attention to

Had to modify the function that builds the @mentions string to put on the beginning of replies to make it so that I don't get a double mention for the person I'm replying to, but other than that it's working pretty smoothly. Thinking of tossing together a pull request tonight.

**Comment by martianhi** [comment]
if anyone passing by confirms that this works for them, let me know and i can merge it. 

i tried with one instance and it didn't work, perhaps because not all pleroma servers actually implmement the mastodon API, if i recall rightly.

**Comment by faried** [comment]
@mooseyboots I can confirm that it's still needed.  I'm on Emacs 27.2, and the latest commit (d4c0d2a2a3013136f5b1fea40ae1e7022f461dd9).

**Comment by martianhi** [comment]
@faried thx, merged.
