### ISSUE TITLE
Use custom emojis

### ISSUE THREAD

**Issue by yisraeldov** [martianhi/mastodon.el#212]
It would be good to download and add custom emojis from the server.

They have an [api](https://mastodon.technology/api/v1/custom_emojis) for fetching emojis.

Emojify has the variable `emojify-user-emojis` that can be used
for adding custom emojis. 

I can probably do this myself, but wanted to open an issue for it.

**Comment by hdurer** [comment]
When do you need that?
When composing toots or for viewing toots of others?

**Comment by yisraeldov** [comment]
Honestly, I don't need that but I assumed that you would have implemented
it.

One would need it when reading messages from others, I assume.

Maybe it should be it's own package.

**Comment by hdurer** [comment]
Should be investigated.  I always assumed that the toots to show are already processed (i.e. the emoji is turned into an `img` tag with the link to the emoji representations and the text version only in the `alt` attributed.  But that is mere assuming; I haven't actually seen this (but also not looked for it).

OTOH, I assume it would be needed when composing a toot so the user can include instance-specific emojis.  There'd be two levels here
  1) just offering the textual name to be included
  2) showing the graphical representation when typed.

For both we'd need the data from the api.

**Comment by yisraeldov** [comment]
If you see the descriptions I posted a link to the api for custom emojis...
Maybe it should be developed as a separate package. I could see it  being
useful outside of mastodon.

What about usernames? I know that some usernames use the custom emojis, are
these also converted to img tags?
