### ISSUE TITLE
When sending toot over 500 char fails loosing the composed toot.

### ISSUE THREAD

**Issue by yisraeldov** [martianhi/mastodon.el#216]
Like it says.

If you try to compose a toot over 512 char, it will fail, with-out giving the option to edit toot.

It should either give the option to edit, or automatically split

**Comment by hdurer** [comment]
Yes, we don't even fetch the configured max toot length (it can vary from server to server).

But it's true that if posting fails we should go back to the toot compose buffer without losing any data.
