### ISSUE TITLE
New toot

### ISSUE THREAD

**Issue by ghost** [martianhi/mastodon.el#234]
Hi, after sending a new toot, I am getting:

"Wrong type argument: number-or-marker-p, nil" error.

version 20190305.344 from MELPA

Should I use the git version instead?

**Comment by justinabrahms** [comment]
```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  mastodon-toot--update-status-fields(50 69 19)
  add-text-properties(50 69 (display "9 minutes ago"))
  mastodon-tl--update-timestamps-callback(#<buffer *mastodon-home*> nil)
  apply(mastodon-tl--update-timestamps-callback (#<buffer *mastodon-home*> nil))
  timer-event-handler([t 24528 26959 0 nil mastodon-tl--update-timestamps-callback (#<buffer *mastodon-home*> nil) nil 0])

```

^^ That's the full trace that I'm seeing.

**Comment by martianhi** [comment]
duplicate of #227. https://github.com/jdenen/mastodon.el/pull/241 fixes it. if you dont want to wait for the pr to be merged you could just add it yourself.
