### ISSUE TITLE
update dec 2021

### ISSUE THREAD

**Issue by mooseyboots** [martianhi/mastodon.el#242]
jdenen recently transferred this repo to me, as i (and recently @hdurer) have been hacking away on a fork for a few months over at https://git.blast.noho.st/mouse/mastodon.el.

PRs #241 and #231 fix the two serious bugs with auth and sending toots.

i added a lot of low-hanging easy features, with fairly amateur coding skills. though we're slowly improving on quality.

for now, i'll make https://git.blast.noho.st/mouse/mastodon.el the canonical repo. if you are interested in collaborating there, write me and i can register you. if needed, we may move it to codeberg.org, for ease of external contributors.

feel free to open new issues here.

and hearty thanks to @jdenen, @alexjgriffith, @ieure and @hdurer for all their sick code from way back. hopefully we'll keep it alive with our tenacious tinkering.

**Comment by abhiseck** [comment]
> for now, i'll make https://git.blast.noho.st/mouse/mastodon.el the canonical repo. if you are interested in collaborating there, write me and i can register you. if needed, we may move it to codeberg.org, for ease of external contributors.

Hello! As we talked on Mastodon, I have been trying to improve login feature (Making login possible with 2FA etc.). Do you think you can add me to your gitea instance?
