### ISSUE TITLE
Create toots with C-c C-c doesn't work, gives this error: Wront type argument: stringp, nil

### ISSUE THREAD

**Issue by trueauracoral** [martianhi/mastodon.el#247]
So, I installed mastodon.el for emacs in the quest to use mastodon without JS. 

The install process was a bit bumpy but after a list-packages and manual install of mastodon it worked for my emacs. I signed in and it was great. Just I go to make a toot and get this error:
![image](https://user-images.githubusercontent.com/87541524/148806255-e5b1ff6e-d9bd-4dd6-8d84-39c5ae326b2d.png)
I can't screenshot the error but basically it shows at the bottom: `Wrong type argument: stringp, nil`

I am confused why this is happening. Am I using somehow a outdated version of mastodon.el from the melpa thing?
![image](https://user-images.githubusercontent.com/87541524/148806502-17504ec6-c1b8-4337-9a94-ac6a39b44416.png)
It shows here tootsuit/mastodon.el and not mooseyboots/mastodon.el. For all I know this isn't even the correct place to put issues. I am just coming here because it seems like this project is not abandoned. Have a nice day whoever is reading this.

**Comment by trueauracoral** [comment]
https://git.blast.noho.st//mouse/mastodon.el Sorry, according to list-packages I am using this. But that gitea repo looks exactly like this github repo.

**Comment by martianhi** [comment]
@trueauracoral it's fine to open issues here.

thanks for trying the package and sorry about the error. if you could enable debugging with `toggle-debug-on-error` then try to toot again, and share the backtrace that it pops up that would be helpful.

also, you mention trying to manually install, and installing from MELPA. if you are unsure of what you did i would probably recommend removing all traces of the package, restarting emacs, and installing again, just from one source. then you know you don't have mixed up code running.

also let me know your emacs version + os.

i currently don't see this error on a clean run of `emacs -Q`, running 27.1.

i can also see `50/nil characters` in your screenshot, which also needs fixing. does `nil` ever change to an integer? it should display your server's maximum toot length.

**Comment by trueauracoral** [comment]
Okay.

**debug command**
It just prints out this:
```lisp
  string-to-number(nil)
  mastodon-toot--send()
  funcall-interactively(mastodon-toot--send)
  call-interactively(mastodon-toot--send nil nil)
  command-execute(mastodon-toot--send)
```

**Emacs version and OS**
I am running emacs 27.1 on windows 10.

I will try reinstalling the mastodon package I guess.

**Nil character**
I have no clue why it doesn't put the maximum amount of characters. On the instance that I use it's 500 word limit.

**Comment by martianhi** [comment]
@trueauracoral thanks for the backtrace and info.

you might also see if hitting `C-g` works before sending the toot, in which case see #227 and PR #241. (hoping not, it rly should be fixed.)

i don't have any windows 10 to test on unfortunately, but i can take another look at the state of the function concerned.

if you still have trouble, perhaps also let me know how bumpy your set up/install process is.

**Comment by trueauracoral** [comment]
**C-g and then C-c C-c**
I do this and I get the same `Wrong type argument: stringp, nil` 

Looking at https://github.com/mooseyboots/mastodon.el/issues/227 it says that they installed the json package? I don't know if I need this package though.

**Windows possibly being the error**
I think that since everything except for making toots/replys works possibly windows isn't the error. Though windows definitely could be a culprit. 

**Bumpy Install**
Originally I put this in my config:
```lisp
(use-package mastodon)
;; mastodon
(setq mastodon-instance-url "https://mastodon.online")
(setq mastodon-auth-source-file "~/.emacs.d/masto")
```
But that didn't work when opening my emacs again and expecting everything to download properly. The package didn't install because it couldn't find it.

So I did a package-install and looked for mastodon, hit enter and the package was installed. Very strange to me. In the screenshot I showed in my first post here. Everything works well except for creating toots.

I am not really sure what's the problem. But my error about `Wrong type argument: stringp, nil` is not what the other issues you sent are talking about. My guess is that the issue stems from the weird counter thing being nil.

**Comment by mooseyboots** [comment]
@trueauracoral, thanks for providing further details.

i took a look a your server's "instance" JSON, and lo and behold, it declares its max characters differently to mine, which i wrote the code against. i pushed a fix just now to the master branch here, so that should work for servers like yours now too.

max char fetching should work, but also tooting should not fail if fetching max chars fails.

**Comment by trueauracoral** [comment]
![image](https://user-images.githubusercontent.com/87541524/149034228-fad58142-4e8d-4d9d-bc1f-356e1cbde301.png)
Everything now works! Hopefully this fix, will help others that have this json issue.

**Comment by mooseyboots** [comment]
feel free to re-open if this crops up again.
