### ISSUE TITLE
If 2FA is enabled, mastodon.el goes into an infinite auth loop

### ISSUE THREAD

**Issue by ksonney** [martianhi/mastodon.el#31]
When a user has 2 Factor Auth enabled, mastodon.el is unable to authenticate and will prompt for the username and password until the user either (a) disables their 2 Factor Auth, or (b) exits emacs. 

Mastodon.el should do one of the following if 2FA is turned on:
- Use OAuth to get a token
- Prompt for the 2FA auth code and submit it for the user
- Cleanly exit/error out so that the user can turn off 2FA

**Comment by jdenen** [comment]
Thanks for the heads up. I wanted to get through authentication as quick as possible so I could get people tooting from Emacs. 

I want to implement the clean exit option to fix this issue. Then I can come back a fully support 2FA post 1.0.0. 

I do consider this a blocking bug in the meantime.
