### ISSUE TITLE
Default "colors" are bot really usable

### ISSUE THREAD

**Issue by bortzmeyer** [martianhi/mastodon.el#38]
The default color for toots is a very pale grey, almost unreadable. The blue for the user names is not much better.

I suggest to change the default and (probably more important) to document how the user could change it (my own preference would be to use the default font/color for everything).

**Comment by bortzmeyer** [comment]
"Not", not "bot" :-(

**Comment by jdenen** [comment]
Yeah, I've been developing this against a dark theme and that has definitely influenced its look. I need to hook into the user's theme. Thanks for bringing this to my attention!

**Comment by jdenen** [comment]
I closed this with a commit. The faces I use should now align with your Emacs theme.

Feel free to reopen if the colors still seem unusable. Documentation about customizing the package will come later.
