### ISSUE TITLE
Display media in timelines

### ISSUE THREAD

**Issue by jdenen** [martianhi/mastodon.el#41]
They just display as links right now.

**Comment by alexjgriffith** [comment]
I have fixed the image in-lining for the most part. Once the final string is prepped in `mastodon-tl--timeline` each `Media_Link:: .*` is replaced with its respective image. 

![screenshot 2017-04-24 01 42 01](https://cloud.githubusercontent.com/assets/6475397/25323720/5c4f2de0-288f-11e7-956f-6a120d63c0f8.png)
