### ISSUE TITLE
IWBN to have automatic refresh

### ISSUE THREAD

**Issue by bortzmeyer** [martianhi/mastodon.el#59]
Apparently, mastodon.el does not automatically refrshes the open timeline: I need to call mastodon-tl--update (which has no key binding by default). Why not a periodic automatic resfresh, with a period configured by a variable?

**Comment by jdenen** [comment]
Update is bound to `u` by default. This is a good idea but should be configurable. 

Maybe turned off by default.

**Comment by martianhi** [comment]
covered by #164 i guess.
