### ISSUE TITLE
JSON readtable error

### ISSUE THREAD

**Issue by rafoo** [martianhi/mastodon.el#68]
Hello,

I have configured mastodon.el as follows:

```
(add-to-list 'load-path "~/.emacs.d/elisp/mastodon/lisp")
(require 'mastodon)
(setq mastodon-instance-url "https://mastodon.zaclys.com")
```

When I then try to `M-x mastodon`, I am asked for my e-mail and password and then get the following error:

```
Contacting host: mastodon.zaclys.com:443
error in process filter: url-http-parse-headers: Wrong type argument: char-or-string-p, nil
error in process filter: Wrong type argument: char-or-string-p, nil
json-read: JSON readtable error
```

My Emacs version is `GNU Emacs 24.4.1 (x86_64-pc-linux-gnu, GTK+ Version 3.14.5) of 2015-03-07 on trouble, modified by Debian`.

Thank you for making this Mastodon Emacs client, I hope that I will soon be able to test it!

**Comment by jdenen** [comment]
`M-x mastodon-register-client` is a relic from the time before there was a major mode. I need to remove it and all references to it in the documentation. I will spin off an issue for that.

I've seen the `JSON readtable error` before, and every time it was caused by flakiness on the instance's part. When the server throws a 500, the API is returning the "fluffy friend" HTML page instead of JSON. Can you try running `mastodon` again. If you get the `readtable error`, hop on the web client and see if the instance is having issues.

Regardless, I need to handle the HTML page better, because the `JSON readtable error` is confusing and unhelpful. This ticket will represent that moving forward.

**Comment by jdenen** [comment]
Spun #69 off of this ticket.

**Comment by jdenen** [comment]
Moving the bit about `mastodon-register-client` to #69

**Comment by jdenen** [comment]
Example response buffer:

```
HTTP/1.1 500 Internal Server Error
Server: nginx
Date: Mon, 24 Apr 2017 11:07:36 GMT
Content-Type: text/html
Content-Length: 990
Connection: close
ETag: "58f7d4bc-3de"

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>We're sorry, but something went wrong</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link href="https://fonts.googleapis.com/css?family=Roboto:400" rel="stylesheet">
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: #282c37;
      color: #9baec8;
      text-align: center;
      margin: 0;
      padding: 20px;
    }

    .dialog img {
      display: block;
      margin: 20px auto;
      margin-top: 50px;
      max-width: 600px;
      width: 100%;
      height: auto;
    }

    .dialog h1 {
      font: 20px/28px -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      font-weight: 400;
    }
  </style>
</head>

<body>
  <div class="dialog">
    <img src="/oops.png" alt="Mastodon" />

    <div>
      <h1>We're sorry, but something went wrong.</h1>
    </div>
  </div>
</body>
</html>
```

**Comment by rafoo** [comment]
Thank you for the fast reply!

> Can you try running mastodon again. If you get the readtable error, hop on the web client and see if the instance is having issues.

I have the following error: `url-http-parse-headers: Wrong type argument: char-or-string-p, nil`, the web client works fine.

> Example response buffer: [...]

Sorry I don't get from where I am supposed to get this, what is the response buffer?

**Comment by jdenen** [comment]
The example response buffer was just reference for me when I (or someone else) works on this issue.

**Comment by emdeesee** [comment]
This problem manifested for me using the following version of emacs:
> "GNU Emacs 24.4.1 (x86_64-pc-linux-gnu, GTK+ Version 3.4.2)                                                                                     
> of 2015-01-11 on maritornes, modified by Debian"

However running this version, I do not have the problem:

> "GNU Emacs 25.1.1 (arm-unknown-linux-gnueabihf, GTK+ Version 3.22.5)
> of 2016-12-31, modified by Debian"

Upgrading emacs, if possible, seems to be a work-around.

**Comment by ksonney** [comment]
This appears to be back with emails 26.0.50.

**Comment by ksonney** [comment]
OK, I did some testing using the current mastodon.el and emacs 26. This seems to occur only when there is an error from mastodon, which comes as HTML and not JSON data. There may need to be more robust error handling for things like password failures, 500 errors, and the like.

**Comment by goodevilgenius** [comment]
I'm getting this error when calling `M-x mastodon` with `(setq mastodon-instance-url "https://mastodon.host")`. I'm not even given an opportunity to enter my email and password.

And the instance seems to be running fine. https://mastodon.host is up and working with no problem.

I'm using version 20190305.344 from melpa, on Emacs 26.1

**Comment by goodevilgenius** [comment]
I tinkered around a bit, and got this from the debugger:

```
Debugger entered--Lisp error: (json-readtable-error 60)
  signal(json-readtable-error (60))
  json-read()
  json-read-from-string("\n<html>\015\n<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>\015\n<body bgcolor=\"white\">\015\n<center><h1>400 Bad Request</h1></center>\015\n<center>The plain HTTP request was sent to HTTPS port</center>\015\n<hr><center>nginx/1.14.1</center>\015\n</body>\015\n</html>\015\n")
  mastodon-client--fetch()
  mastodon-client--store()
  mastodon-client()
  (progn (mastodon-client))
  eval((progn (mastodon-client)) t)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

It looks like, even though my instance url is set to `https://mastodon.host`, it looks like it's actually requesting `http://mastodon.host:443`.

I can reproduce this response externally from my shell:

```
$ http -v POST http://mastodon.host:443/oauth/token 
POST /oauth/token HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 0
Host: mastodon.host:443
User-Agent: HTTPie/0.9.4



HTTP/1.1 400 Bad Request
Connection: close
Content-Length: 271
Content-Type: text/html
Date: Wed, 13 Mar 2019 15:35:23 GMT
Server: nginx/1.14.1

<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx/1.14.1</center>
</body>
</html>
```

**Comment by sch1z00** [comment]
on Emacs 25.2.2 and mastodon-20190305.344 (from Melpa)

> Debugger entered--Lisp error: (json-readtable-error)
>   signal(json-readtable-error nil)
>   json-read()
>   json-read-from-string("\n<html>
> \n<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
> \n<body bgcolor=\"white\">
> \n<center><h1>400 Bad Request</h1></center>
> \n<center>The plain HTTP request was sent to HTTPS port</center>
> \n<hr><center>cloudflare</center>
> \n</body>
> \n</html>
> \n")
>   mastodon-auth--get-token()
>   mastodon-auth--access-token()
>   mastodon-http--get("https://xxx.social//api/v1/timelines/home")
>   mastodon-http--get-json("https://xxx.social//api/v1/timelines/home")
>   mastodon-tl--init("home" "timelines/home" mastodon-tl--timeline)
>   mastodon-tl--get-home-timeline()
>   mastodon()
>   funcall-interactively(mastodon)
>   call-interactively(mastodon record nil)
>   command-execute(mastodon record)
>   execute-extended-command(nil "mastodon" "masto")
>   funcall-interactively(execute-extended-command nil "mastodon" "masto")
>   call-interactively(execute-extended-command nil nil)
>   command-execute(execute-extended-command)
>

**Comment by martianhi** [comment]
ieure@50062c5 fixes this, i think, with error handling
