### ISSUE TITLE
Fold content below CW

### ISSUE THREAD

**Issue by jdenen** [martianhi/mastodon.el#83]
Hide everything but spoiler text in a toot with a content warning.

**Comment by alexjgriffith** [comment]
I have folding and unfolding content working. Going forward however, I think we should refactor how the toots are rendered.

**Comment by hdurer** [comment]
I also have some code that works with my tabbing navigation logic if have.

**Comment by alexjgriffith** [comment]
One more request, could we bind `c` to a function that attempts to toggle a cw on and off in the current toot?

**Comment by alexjgriffith** [comment]
closed by #184
