### ISSUE TITLE
Should there be a develop branch?

### ISSUE THREAD

**Issue by jdenen** [martianhi/mastodon.el#86]
Some context:

1. `MELPA` builds master `HEAD`. 
2. `MELPA-stable` builds the latest tag refspec.
3. A vast majority of users pull from `MELPA` not `MELPA-stable`.

Using master as a working branch seems like a risk now. For example, I'd like to merge #73, tinker and tweak it. But that seems unwise given the MELPA/stable dynamic.

We could alleviate the risk by moving work to a develop branch and following a simplified GitFlow branching strategy. 

If we do this, do we continue to tag master often (just about every push)? This keeps MELPA/stable at the same version essentially.

Or do we treat tagged releases as much bigger deals? Only do them every so often and let the master branch be a release-candidate version?

**Comment by alexjgriffith** [comment]
I am pro having a develop branch. 

I have never worked with a simplified GitFlow branching strategy but I have read [an example](http://nvie.com/posts/a-successful-git-branching-model/) previously, (conveniently the first hit on google for GitFlow branching strategy), and it seams like a sane approach.

As for tagging the master (i.e., releasing to melpa) as a rule of thumb you could do it when any feature is implemented that requires an entry in the README.md. If people want the bleeding edge nightly they can clone the master branch.

**Comment by jdenen** [comment]
I agree that there should be a develop branch. I'm going to create it today.
