### ISSUE TITLE
GNU plus Social support

### ISSUE THREAD

**Issue by yuvallanger** [martianhi/mastodon.el#88]
[GNU plus Social] is another implementation of the server ([Git repo]) within the microblogging fediverse. Can this client be used to interact with the GNU plus Social class of servers?

[GNU plus Social]: <https://gnu.io/social/>
[Git repo]: <https://git.gnu.io/explore/projects>

**Comment by jdenen** [comment]
I'm not sure. It's worth looking into though.

**Comment by alexjgriffith** [comment]
While the request response content should be consistent between both, I don't believe the API implemented for mastodon is consistent with GNU Social, [see](https://github.com/tootsuite/mastodon/issues/176). A separate API interface would have to be implemented to accommodate this.

**Comment by clacke** [comment]
https://www.emacswiki.org/emacs/identica-mode.el already exists.

**Comment by jdenen** [comment]
I'm closing this ticket given the feedback from @alexjgriffith and @clacke
