### ISSUE TITLE
M-x mastodon hangs when connecting to cybre.space

### ISSUE THREAD

**Issue by clarkenciel** [martianhi/mastodon.el#89]
I have the following configuration:
`(setq mastodon-instance-url "https://cybre.space")`

and when I run `mastodon` emacs just hangs for a long time until I quit the process.

**Comment by alexjgriffith** [comment]
It looks like registration for cybre.space is down for an hour.

Could you try to run `M-x mastodon` again? When I tried to access the site a few minutes ago from the browser it hung, but it seams to be available again.

**Comment by clarkenciel** [comment]
@alexjgriffith no dice and this has happened every time i've tried running the command. I'm able to log in just fine on the site with my credentials and i'm not using 2fa.

**Comment by alexjgriffith** [comment]
Just a few questions.
1. Did it ask your user name and password the first time you tried to access this instance?

2. Did you enter your username and password before setting `mastodon-instance-url` to "https://cybre.space"?

If either of these are true your credentials are set to the the previous instance of mastodon, mastodon.social by default.

Try running the following in your *scratch* it will request a new token for the server.
 ```
(mastodon-auth--get-token)
```

**Comment by jdenen** [comment]
You'd need to do a bit more to get back to a clean state than that. The best way to be sure is to delete `mastodon.plstore` from your Emacs config directory and then restart Emacs. 

But I don't think the client credentials are the issue here. It sounds like Tusky had a problem with this instance too.

**Comment by clarkenciel** [comment]
@jdenen removing the `mastodon.plstore` file and rerunning did the trick. I must have accidentally provided my credentials for the default instance as @alexjgriffith describes. Thank you so much for the time and help!
