### ISSUE TITLE
Support favorites list

### ISSUE THREAD

**Issue by clarkenciel** [martianhi/mastodon.el#91]
Support actions against the [`GET /api/v1/favourites`](https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#favourites) endpoint would be nifty.

**Comment by jdenen** [comment]
This feels like a pretty easy thing to do. It seems like just another timeline.

Added it to the 1.0.0 milestone.

**Comment by alexjgriffith** [comment]
Implementing this feature requires us to capture the `max_id` and the `since_id` in the response header, i.e. we will need to rework how we handle the response from `url-retrieve-synchronously`. 

Perhaps at the same time we can make the call asynchronous?

[From Mastodon API Documentation](https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#favourites)

> Note: max_id and since_id for next and previous pages are provided in the Link header. It is not possible to use the id of the returned objects to construct your own URLs, because the results are sorted by an internal key.

Edit: See #197
